# SITE CONFIGURATION
baseurl: "/portfolio" # the subpath of your site, e.g. /blog/
url: "/portfolio" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Makarand Pande
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Full Stack Web Developer</h1>
  header_text_feature_image:
  footer_text: >
   Powered by Makarand Pande 2015 Bloc Student

  # Icons
  rss: false
  email_address: "mak_pande@yahoo.com" # Full email address
  behance:
  bitbucket:
  dribbble:
  facebook: "makarand.pande.7"
  flickr:
  github: "makpande"
  google_plus:
  instagram:
  linkedin:  "/in/makpande2015"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "mak_pande"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
